# Plantilla: docker-compose.yml para PostgreSQL
version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: focus_draft_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin #CAMBIAR EN PRODUCCION
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U focus_draft_user -d focus_draft_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
